# Generated by Django 5.2.14 on 2026-05-28 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('weekly_limit', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('monthly_limit', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('pending_daily_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('pending_weekly_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('pending_monthly_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('limit_change_available_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_limit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SelfExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('7_days', '7 days'), ('30_days', '30 days'), ('90_days', '90 days'), ('indefinite', 'Indefinite')], max_length=20)),
                ('starts_at', models.DateTimeField(auto_now_add=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='self_exclusion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
