# Generated by Django 5.2.14 on 2026-05-28 07:20

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=120)),
                ('away_team', models.CharField(max_length=120)),
                ('start_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('programado', 'Programado'), ('en_vivo', 'En vivo'), ('finalizado', 'Finalizado'), ('suspendido', 'Suspendido'), ('anulado', 'Anulado')], default='programado', max_length=20)),
                ('result', models.CharField(blank=True, choices=[('gana_local', 'Gana local'), ('empate', 'Empate'), ('gana_visitante', 'Gana visitante')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Odd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.CharField(choices=[('gana_local', 'Gana local'), ('empate', 'Empate'), ('gana_visitante', 'Gana visitante')], max_length=20)),
                ('decimal_odds', models.DecimalField(decimal_places=4, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='betting.event')),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('selection', models.CharField(choices=[('gana_local', 'Gana local'), ('empate', 'Empate'), ('gana_visitante', 'Gana visitante')], max_length=20)),
                ('stake', models.DecimalField(decimal_places=4, max_digits=18)),
                ('odds_snapshot', models.DecimalField(decimal_places=4, max_digits=18)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('won', 'Won'), ('lost', 'Lost'), ('cancelled', 'Cancelled'), ('cashed_out', 'Cashed out')], default='accepted', max_length=20)),
                ('payout', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='betting.event')),
                ('odd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bets', to='betting.odd')),
            ],
        ),
        migrations.AddConstraint(
            model_name='odd',
            constraint=models.UniqueConstraint(fields=('event', 'selection'), name='uniq_event_selection_odd'),
        ),
    ]
