# Generated by Django 5.2.14 on 2026-05-28 20:35

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='odd',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='CombinedBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('stake', models.DecimalField(decimal_places=4, max_digits=18)),
                ('odds_snapshot', models.DecimalField(decimal_places=4, max_digits=18)),
                ('selection_count', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('won', 'Won'), ('lost', 'Lost'), ('cancelled', 'Cancelled'), ('cashed_out', 'Cashed out')], default='accepted', max_length=20)),
                ('payout', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combined_bets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CombinedBetSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.CharField(choices=[('gana_local', 'Gana local'), ('empate', 'Empate'), ('gana_visitante', 'Gana visitante')], max_length=20)),
                ('odds_snapshot', models.DecimalField(decimal_places=4, max_digits=18)),
                ('combined_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='betting.combinedbet')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.event')),
                ('odd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='betting.odd')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('combined_bet', 'event'), name='uniq_combined_bet_event')],
            },
        ),
    ]
