# Generated by Django 5.2.14 on 2026-05-29 06:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0002_odd_updated_at_combinedbet_combinedbetselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_bets_per_user',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='event',
            name='max_event_exposure',
            field=models.DecimalField(decimal_places=4, default=Decimal('10000.0000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='event',
            name='max_total_bets',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='event',
            name='sport',
            field=models.CharField(choices=[('futbol', 'Futbol'), ('basquet', 'Basquet'), ('tenis', 'Tenis'), ('voley', 'Voley')], default='futbol', max_length=20),
        ),
        migrations.AddField(
            model_name='odd',
            name='max_selection_exposure',
            field=models.DecimalField(decimal_places=4, default=Decimal('5000.0000'), max_digits=18),
        ),
    ]
