# Generated by Django 5.2.14 on 2026-05-29 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0003_merge_20260528_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selection',
            options={'verbose_name': 'selección', 'verbose_name_plural': 'selecciones'},
        ),
        migrations.AddField(
            model_name='event',
            name='max_event_exposure',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='exposición máxima del evento'),
        ),
        migrations.AddField(
            model_name='market',
            name='max_bets',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='máximo de apuestas'),
        ),
        migrations.AddField(
            model_name='market',
            name='max_exposure',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='exposición máxima'),
        ),
        migrations.AddField(
            model_name='market',
            name='suspended_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='suspendido hasta'),
        ),
        migrations.AlterField(
            model_name='accumulatedbetleg',
            name='selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accumulator_legs', to='betting.selection', verbose_name='selección'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='dirección IP'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bets', to='betting.selection', verbose_name='selección'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sport',
            field=models.CharField(choices=[('futbol', 'Fútbol'), ('basquet', 'Básquet'), ('voley', 'Vóley')], max_length=100, verbose_name='deporte'),
        ),
        migrations.AlterField(
            model_name='market',
            name='market_type',
            field=models.CharField(choices=[('1X2', '1X2'), ('over_under', 'Over/Under'), ('btts', 'Both teams to score'), ('winner', 'Ganador'), ('handicap', 'Hándicap'), ('totals', 'Totales'), ('sets', 'Sets')], max_length=20, verbose_name='tipo'),
        ),
    ]
