# Generated by Django 5.2.14 on 2026-05-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0004_alter_selection_options_event_max_event_exposure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='live_betting_enabled',
            field=models.BooleanField(default=True, verbose_name='apuestas en vivo habilitadas'),
        ),
        migrations.AddField(
            model_name='event',
            name='max_bets',
            field=models.PositiveIntegerField(default=5000, verbose_name='límite máximo de apuestas'),
        ),
    ]
