# Generated by Django 5.2.14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dni", models.CharField(max_length=8, unique=True)),
                ("fecha_nacimiento", models.DateField()),
                (
                    "estado_kyc",
                    models.CharField(
                        choices=[
                            ("pendiente_verificacion", "Pendiente de verificación"),
                            ("verificado", "Verificado"),
                            ("bloqueado", "Bloqueado"),
                            ("autoexcluido", "Autoexcluido"),
                        ],
                        default="pendiente_verificacion",
                        max_length=32,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "perfil de usuario",
                "verbose_name_plural": "perfiles de usuario",
            },
        ),
    ]
