# Generated by Django 5.2.14 on 2026-05-28 06:58

import apps.users.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True, validators=[apps.users.validators.validate_peruvian_dni])),
                ('birth_date', models.DateField(validators=[apps.users.validators.validate_adult_birth_date])),
                ('kyc_status', models.CharField(choices=[('pendiente_verificacion', 'Pendiente de verificación'), ('verificado', 'Verificado'), ('bloqueado', 'Bloqueado'), ('autoexcluido', 'Autoexcluido')], default='pendiente_verificacion', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
