# Generated by Django 5.2.14 on 2026-05-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='welcome_bonus_granted',
            field=models.BooleanField(default=False, verbose_name='bono de bienvenida otorgado'),
        ),
    ]
