# Generated by Django 5.2.14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("wallet_usuario", "Wallet del usuario"),
                            ("casa", "Casa"),
                            ("apuestas_pendientes", "Apuestas pendientes"),
                            ("bonos", "Bonos"),
                        ],
                        max_length=25,
                        verbose_name="tipo de cuenta",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creada en")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "cuenta",
                "verbose_name_plural": "cuentas",
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=4, max_digits=18, verbose_name="monto")),
                (
                    "direction",
                    models.CharField(
                        choices=[("DEBIT", "Debito"), ("CREDIT", "Credito")],
                        max_length=6,
                        verbose_name="direccion",
                    ),
                ),
                ("transaction_id", models.CharField(db_index=True, max_length=120, verbose_name="ID de transaccion")),
                ("description", models.CharField(blank=True, default="", max_length=255, verbose_name="descripcion")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="creado en")),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="wallet.account",
                        verbose_name="cuenta",
                    ),
                ),
            ],
            options={
                "verbose_name": "entrada del libro mayor",
                "verbose_name_plural": "entradas del libro mayor",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user", "type"),
                name="unique_account_per_user_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", True)),
                fields=("type",),
                name="unique_global_account_type",
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(fields=["account", "direction"], name="idx_ledger_account_direction"),
        ),
    ]
